name:                tlvmmt
version:             0.1.0.0
github:              "superfashi/tlvmmt"
license:             0BSD
author:              "SuperFashi"
maintainer:          "admin@superfashi.com"
copyright:           "2023 SuperFashi"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/superfashi/tlvmmt#readme>

dependencies:
- base >= 4.15 && < 5
- binary
- bytestring

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - extra

executables:
  tlvmmt-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tlvmmt
    - list-t
    - transformers
    - pretty-show

tests:
  tlvmmt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tlvmmt
